### PR TITLE
PHPFOL-5 doc: add  makefile

### PR DESCRIPTION
**Pull request by Tenekonate**

### CODE REVIEW

**Review by Dev-Int — APPROVED** [review]

**Review by JasonBenett — CHANGES_REQUESTED** [review]
Why did you moved the docker-compose file from the docker folder to the root ?

**Comment by Dev-Int** [comment]
It's me. 
I think it's better to run with Makefile.

**Comment by JasonBenett** [comment]
> It's me. 
> I think it's better to run with Makefile. 
> 
> Ps: but... I understand why you prefer in docker folder 😉😇

Why would it be better ? Moreover, it's probably "broken" in reality because we are not using the .env file anymore.

**Comment by Dev-Int** [comment]
> Why would it be better ? ~Moreover, it's probably "broken" in reality because we are not using the .env file anymore.~ I saw you moved the .env too. Should not be the case neither.

As I said before, now I understand why you prefer in `docker` folder. We don't need it in the library. Only for dev. :wink:

**Comment by Tenekonate** [comment]
> > Why would it be better ? ~Moreover, it's probably "broken" in reality because we are not using the .env file anymore.~ I saw you moved the .env too. Should not be the case neither.
> 
> As I said before, now I understand why you prefer in `docker` folder. We don't need it in the library. Only for dev. 😉

so we will work inside the docker folder ? I saw that the makefile should be set to the main

**Review by Dev-Int — APPROVED** [review]

**Review by JasonBenett — APPROVED** [review]

**Pull request merged**
